name: Generate Config File

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate-config:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Generate config.js
      run: |
        echo "const API_KEY = '${{ secrets.API_KEY }}';" > js/config.js

    - name: Commit and push config.js
      uses: EndBug/add-and-commit@v9
      with:
        add: 'js/config.js'
        message: 'Add generated config.js file'
        branch: main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
